use_frameworks!

platform :ios, '8.0'

target 'LZGridViewCheckTool_Example' do
  pod 'LZGridViewCheckTool', :path => '../'

  target 'LZGridViewCheckTool_Tests' do
    inherit! :search_paths

    
  end
end
